-- CreateTable
CREATE TABLE "Delegacion" (
    "id" SERIAL NOT NULL,
    "anio_ingreso" INTEGER,
    "orden" INTEGER,
    "mes_ingreso" TEXT,
    "numero_investigacion_previa" VARCHAR(255),
    "numero_instruccion_fiscal" VARCHAR(255),
    "zona" VARCHAR(255),
    "provincia" VARCHAR(255),
    "canton" VARCHAR(255),
    "cod_distrito" VARCHAR(255),
    "distrito" VARCHAR(255),
    "grado_agente" VARCHAR(255) NOT NULL,
    "apellidos_nombres_agente" VARCHAR(255) NOT NULL,
    "tipo_delito" VARCHAR(255),
    "delito_tipificado_delegacion" VARCHAR(255),
    "delito_desagregacion_policia_judicial" VARCHAR(255),
    "fecha_infraccion_delito" TIMESTAMP(3),
    "apellidos_nombres_victima" VARCHAR(255),
    "sexo_victima" VARCHAR(255),
    "edad_victima" INTEGER,
    "apellidos_nombres_sospechoso" VARCHAR(255),
    "condicion_infractor_involucrado" VARCHAR(255),
    "parentesco_detenido_sospechoso_victima" VARCHAR(255),
    "alias_sospechoso" VARCHAR(255),
    "placa_vehiculo_involucrado" VARCHAR(255),
    "apellidos_nombres_fiscal" VARCHAR(255),
    "unidad_especializada" VARCHAR(255),
    "fecha_delegacion" TIMESTAMP(3),
    "fecha_recepcion_pj" TIMESTAMP(3),
    "fecha_recepcion_agente_investigador" TIMESTAMP(3),
    "no_oficio_recibe_diligencia" VARCHAR(255),
    "plazo_otorgado_dias" INTEGER,
    "numero_articulo" VARCHAR(255),
    "articulos_cumplidos" VARCHAR(255),
    "cumplimiento_parcial" VARCHAR(255),
    "cumplimiento_total" VARCHAR(255),
    "fecha_cumplimiento" TIMESTAMP(3),
    "en_investigacion" VARCHAR(255),
    "numero_oficio_descargo" VARCHAR(255),
    "versiones" INTEGER,
    "reconocimientos_lugar_hechos" INTEGER,
    "determino_posibles_responsables" VARCHAR(255),
    "comparecencia_sospechoso" VARCHAR(255),
    "peticiones_fiscalia" VARCHAR(255),
    "tipo_peticion" VARCHAR(255),
    "no_boletas_solicitadas" INTEGER,
    "nombre_requerido_boleta" VARCHAR(255),
    "no_detenidos_producto_investigacion" INTEGER,
    "apellidos_nombres_detenidos_producto" VARCHAR(255),
    "allanamientos_numero" INTEGER,
    "recuperacion_bienes_evidencias" INTEGER,
    "recuperacion_automotores" INTEGER,
    "recuperacion_otros" INTEGER,
    "peritajes" INTEGER,
    "notificaciones" INTEGER,
    "citaciones" INTEGER,
    "traslados" INTEGER,
    "informe_descargo" VARCHAR(255),
    "causas_incumplimiento_investigacion" VARCHAR(255),
    "nombre_detenidos_producto_investigacion" VARCHAR(255),
    "observaciones" VARCHAR(255),
    "cantidad_sustraida" VARCHAR(255),
    "entidad_financiera" VARCHAR(255),

    CONSTRAINT "Delegacion_pkey" PRIMARY KEY ("id")
);
